wordpress_sites:
  goodfortunes716.com:
    site_hosts:
      -
        canonical: goodfortunes716.test
        redirects:
          - www.goodfortunes716.test
    local_path: ../sites/goodfortunes716.com
    admin_email: admin@goodfortunes716.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
  gourmasianbuffalo.com:
    site_hosts:
      -
        canonical: gourmasianbuffalo.test
        redirects:
          - www.gourmasianbuffalo.test
    local_path: ../sites/gourmasianbuffalo.com
    admin_email: admin@gourmasianbuffalo.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
  obst-farm.com:
    site_hosts:
      -
        canonical: obst-farm.test
        redirects:
          - www.obst-farm.test
    local_path: ../sites/obst-farm.com
    admin_email: admin@obst-farm.test
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
  trivitro.com:
    site_hosts:
      -
        canonical: trivitro.test
        redirects:
          - www.trivitro.test
    local_path: ../sites/trivitro.com
    admin_email: admin@trivitro.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
