wordpress_sites:
  example.com:
    site_hosts:
      -
        canonical: example.dev
        redirects:
          - www.example.dev
    local_path: ../sites/example.com
    admin_email: admin@example.dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
