wordpress_sites:
  goodfortunes716.com:
    site_hosts:
      -
        canonical: goodfortunes716.com
        redirects:
          - www.goodfortunes716.com
    local_path: ../sites/goodfortunes716.com
    repo: 'git@bitbucket.org:krez_freas/goodfortunes716.com.git'
    branch: production
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
      hsts_include_subdomains: false
    cache:
      enabled: false
    theme:
      version: sage-9
      folder: goodfortunes716-theme
  gourmasianbuffalo.com:
    site_hosts:
      -
        canonical: gourmasianbuffalo.com
        redirects:
          - www.gourmasianbuffalo.com
    local_path: ../sites/gourmasianbuffalo.com
    repo: 'git@bitbucket.org:krez_freas/gourmasian.git'
    branch: production
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    theme:
      version: sage-8
      folder: gourmasian-theme
  obst-farm.com:
    site_hosts:
      -
        canonical: obst-farm.com
        redirects:
          - www.obst-farm.com
    local_path: ../sites/obst-farm.com
    repo: 'git@bitbucket.org:krez_freas/obst-farm.git'
    branch: production
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    theme:
      version: sage-8
      folder: obst-farm-theme
  trivitro.com:
    site_hosts:
      -
        canonical: trivitro.com
        redirects:
          - www.trivitro.com
          - vitroclean.com
          - www.vitroclean.com
    local_path: ../sites/trivitro.com
    repo: 'git@bitbucket.org:krez_freas/trivitro.git'
    branch: production
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    theme:
      version: sage-8
      folder: trivitro-theme
    nginx_wordpress_site_conf: nginx-includes/trivitro.com.conf.child
