wordpress_sites:
  goodfortunes716.com:
    site_hosts:
      -
        canonical: goodfortunes716.krez.me
    local_path: ../sites/goodfortunes716.com
    repo: 'git@bitbucket.org:krez_freas/goodfortunes716.com.git'
    branch: dev
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    theme:
      version: sage-9
      folder: goodfortunes716-theme
  gourmasianbuffalo.com:
    site_hosts:
      -
        canonical: gourmasianbuffalo.krez.me
    local_path: ../sites/gourmasianbuffalo.com
    repo: 'git@bitbucket.org:krez_freas/gourmasian.git'
    branch: dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    theme:
      version: sage-8
      folder: gourmasian-theme
  obst-farm.com:
    site_hosts:
      -
        canonical: obst-farm.krez.me
    local_path: ../sites/obst-farm.com
    repo: 'git@bitbucket.org:krez_freas/obst-farm.git'
    branch: dev
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    theme:
      version: sage-8
      folder: obst-farm-theme
  trivitro.com:
    site_hosts:
      -
        canonical: trivitro.krez.me
    local_path: ../sites/trivitro.com
    repo: 'git@bitbucket.org:krez_freas/trivitro.git'
    branch: dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    theme:
      version: sage-8
      folder: trivitro-theme
